on:
  push:
  pull_request:

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.head_ref }}"
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: dom, curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, intl
          coverage: none
      - run: composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_PASSWORD }}"
      - run: composer install --no-interaction --ignore-platform-reqs --no-scripts
      - run: vendor/bin/php-cs-fixer fix --using-cache=no --config=.php_cs.dist --dry-run

  tlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: dom, curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, intl
          coverage: none
      - run: composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_PASSWORD }}"
      - run: composer install --no-interaction --ignore-platform-reqs --no-scripts
      - run: vendor/bin/tlint lint ./app --no-interaction -v

  deploy:
    if: github.event_name == 'push' && false
    needs:
      - phpcs
      - tlint
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://opendor.me

    steps:
      - uses: appleboy/ssh-action@master
        env:
          SSH_ROOT: ${{ secrets.SSH_ROOT }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          envs: "SSH_ROOT"
          script: |
            cd $SSH_ROOT
            git pull origin main
            yarn install
            yarn production
            composer update --no-interaction --prefer-dist --optimize-autoloader --no-dev
            sudo -S service php8.0-fpm reload
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan event:cache
            php artisan migrate --force
            php artisan permission:cache-reset
            php artisan permission:ensure
            php artisan schedule-monitor:sync
            php artisan horizon:terminate

      - uses: srt32/uptime@master
        with:
          url-to-hit: "https://opendor.me"
          expected-statuses: "200"

      - uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: '🚀 Deployment finished for `${{ github.sha }}`'

      - uses: Ilshidur/action-discord@master
        if: ${{ failure() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: '💣️ Deployment failed for `${{ github.sha }}`'

