on:
  push:

jobs:
  pest:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      BROADCAST_DRIVER: log
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
      DB_CONNECTION: pgsql
      DB_HOST: localhost
      DB_PASSWORD: postgres
      DB_USERNAME: postgres
      DB_DATABASE: postgres
    services:
      postgres:
        image: postgres:13-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: 8.0
          extensions: dom, curl, mbstring, zip, pcntl, intl
          coverage: xdebug
      - run: composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_PASSWORD }}"
      - run: composer config "http-basic.satis.laravel-enlightn.com" "${{ secrets.ENLIGHTN_USERNAME }}" "${{ secrets.ENLIGHTN_PASSWORD }}"
      - run: composer install --no-interaction --ignore-platform-reqs --no-scripts
      - run: vendor/bin/pest --coverage-html=.coverage --coverage-text
      - uses: actions/upload-artifact@v2
        with:
          name: Coverage
          path: ./.coverage
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Logs
          path: ./storage/logs
